### ISSUE TITLE
References not found

### ISSUE THREAD

**Issue by carnould** [badulescub/Demo#1]
Hi,

I just downloaded your project, i can t compile it, references missing
using System.Web.Http;
using Microsoft.Azure.Mobile.Server.Login;
using Microsoft.Azure.Mobile.Server.Config
using System.Web.Http.Cors;
using System.Web.Http.Tracing;
using Microsoft.Azure.Mobile.Server;

...

My Temporary fix  is to create a new Mobile Project, then get the reference path on each reference from the new project, remove the one from the old one then add it with the new path ... Really long.

Can you help me to fix the problem?

**Comment by carnould** [comment]
My finale fix is to create a new Mobile App Project and transfer all the files and update the web.config.

**Comment by badulescub** [comment]
Hello, all you should do is restore your nu-get references. Visual Studio should do so automatically on build. References added through another project would only solve your issue locally. NuGet is your answer.

**Comment by carnould** [comment]
I already restored the nugget package, but it didnt work. The only solution working i found was to create a new project then import the cs and config file to the new solution.
